In [143]:
import pandas as pd

In [144]:
df = pd.read_csv("../data/NYC Accidents 2020.csv")

In [145]:
str_columns = ['borough','location', 'on street name', 'cross street name',
       'off street name', 'contributing factor vehicle 1',
       'contributing factor vehicle 2', 'contributing factor vehicle 3',
       'contributing factor vehicle 4', 'contributing factor vehicle 5', 'vehicle type code 1', 'vehicle type code 2',
       'vehicle type code 3', 'vehicle type code 4', 'vehicle type code 5',"month"]

In [146]:
df.columns = df.columns.str.lower()

df["crash date"] = pd.to_datetime(df["crash date"])
df["crash time"] = pd.to_datetime(df["crash time"],format='%H:%M:%S')
df["month"] = df["crash date"].dt.month_name()

df[str_columns] = df[str_columns].apply(lambda x : x.str.lower())

In [147]:
df["hour_of_collision"] = df["crash time"].dt.hour

In [148]:
def get_period(hour):
    if hour < 6:
        return "night"
    elif hour < 12:
        return "morning"
    elif hour < 18:
        return "afternoon"
    else:
     return "evening"

df["time_period"] = df["hour_of_collision"].map(get_period)

In [149]:
df.columns

Index(['crash date', 'crash time', 'borough', 'zip code', 'latitude',
       'longitude', 'location', 'on street name', 'cross street name',
       'off street name', 'number of persons injured',
       'number of persons killed', 'number of pedestrians injured',
       'number of pedestrians killed', 'number of cyclist injured',
       'number of cyclist killed', 'number of motorist injured',
       'number of motorist killed', 'contributing factor vehicle 1',
       'contributing factor vehicle 2', 'contributing factor vehicle 3',
       'contributing factor vehicle 4', 'contributing factor vehicle 5',
       'collision_id', 'vehicle type code 1', 'vehicle type code 2',
       'vehicle type code 3', 'vehicle type code 4', 'vehicle type code 5',
       'month', 'hour_of_collision', 'time_period'],
      dtype='str')

In [150]:
df.head()

,crash date,crash time,borough,zip code,latitude,longitude,location,on street name,cross street name,off street name,...,contributing factor vehicle 5,collision_id,vehicle type code 1,vehicle type code 2,vehicle type code 3,vehicle type code 4,vehicle type code 5,month,hour_of_collision,time_period
0,2020-08-29,1900-01-01 15:40:00,bronx,10466.0,40.89210,-73.833760,point (-73.83376 40.8921),pratt avenue,strang avenue,NaN,...,NaN,4342908,sedan,station wagon/sport utility vehicle,NaN,NaN,NaN,august,15,afternoon
1,2020-08-29,1900-01-01 21:00:00,brooklyn,11221.0,40.69050,-73.919914,point (-73.919914 40.6905),bushwick avenue,palmetto street,NaN,...,NaN,4343555,sedan,sedan,NaN,NaN,NaN,august,21,evening
2,2020-08-29,1900-01-01 18:20:00,NaN,NaN,40.81650,-73.946556,point (-73.946556 40.8165),8 avenue,NaN,NaN,...,NaN,4343142,station wagon/sport utility vehicle,NaN,NaN,NaN,NaN,august,18,evening
3,2020-08-29,1900-01-01 00:00:00,bronx,10459.0,40.82472,-73.892960,point (-73.89296 40.82472),NaN,NaN,1047 simpson street,...,NaN,4343588,station wagon/sport utility vehicle,station wagon/sport utility vehicle,sedan,motorcycle,NaN,august,0,night
4,2020-08-29,1900-01-01 17:10:00,brooklyn,11203.0,40.64989,-73.933890,point (-73.93389 40.64989),NaN,NaN,4609 snyder avenue,...,NaN,4342953,sedan,sedan,NaN,NaN,NaN,august,17,afternoon

In [151]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 74881 entries, 0 to 74880
Data columns (total 32 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   crash date                     74881 non-null  datetime64[us]
 1   crash time                     74881 non-null  datetime64[us]
 2   borough                        49140 non-null  str
 3   zip code                       49134 non-null  float64
 4   latitude                       68935 non-null  float64
 5   longitude                      68935 non-null  float64
 6   location                       68935 non-null  str
 7   on street name                 55444 non-null  str
 8   cross street name              35681 non-null  str
 9   off street name                19437 non-null  str
 10  number of persons injured      74881 non-null  int64
 11  number of persons killed       74881 non-null  int64
 12  number of pedestrians injured  74881 non-null  int64
 13  number of pedestrians killed   74881 non-null  int64
 14  number of cyclist injured      74881 non-null  int64
 15  number of cyclist killed       74881 non-null  int64
 16  number of motorist injured     74881 non-null  int64
 17  number of motorist killed      74881 non-null  int64
 18  contributing factor vehicle 1  74577 non-null  str
 19  contributing factor vehicle 2  59285 non-null  str
 20  contributing factor vehicle 3  6765 non-null   str
 21  contributing factor vehicle 4  1851 non-null   str
 22  contributing factor vehicle 5  523 non-null    str
 23  collision_id                   74881 non-null  int64
 24  vehicle type code 1            74246 non-null  str
 25  vehicle type code 2            53638 non-null  str
 26  vehicle type code 3            6424 non-null   str
 27  vehicle type code 4            1771 non-null   str
 28  vehicle type code 5            503 non-null    str
 29  month                          74881 non-null  str
 30  hour_of_collision              74881 non-null  int32
 31  time_period                    74881 non-null  str
dtypes: datetime64[us](2), float64(3), int32(1), int64(9), str(17)
memory usage: 27.2 MB

In [152]:
contributing_factor=[ 'contributing factor vehicle 1',
       'contributing factor vehicle 2', 'contributing factor vehicle 3',
       'contributing factor vehicle 4', 'contributing factor vehicle 5']

In [153]:
street = ["on street name","cross street name","off street name"]

In [154]:
vehicle_type_code = [ 'vehicle type code 1', 'vehicle type code 2',
       'vehicle type code 3', 'vehicle type code 4', 'vehicle type code 5']

In [155]:
Nan_contributing_factor = df.iloc[df["contributing factor vehicle 1"].isna()]
Nan_contributing_factor

,crash date,crash time,borough,zip code,latitude,longitude,location,on street name,cross street name,off street name,...,contributing factor vehicle 5,collision_id,vehicle type code 1,vehicle type code 2,vehicle type code 3,vehicle type code 4,vehicle type code 5,month,hour_of_collision,time_period
119,2020-08-29,1900-01-01 00:00:00,queens,11385.0,40.700405,-73.905400,point (-73.9054 40.700405),NaN,NaN,1723 cornelia street,...,NaN,4342891,NaN,NaN,NaN,NaN,NaN,august,0,night
196,2020-08-29,1900-01-01 02:10:00,NaN,NaN,40.829990,-73.848870,point (-73.84887 40.82999),cross bronx expressway,watson avenue,NaN,...,NaN,4343269,NaN,NaN,NaN,NaN,NaN,august,2,night
629,2020-08-27,1900-01-01 04:45:00,bronx,10468.0,40.871002,-73.893845,point (-73.893845 40.871002),jerome avenue,morris avenue,NaN,...,NaN,4342218,NaN,NaN,NaN,NaN,NaN,august,4,night
656,2020-08-27,1900-01-01 21:15:00,NaN,NaN,40.705580,-73.739716,point (-73.739716 40.70558),springfield boulevard,112 avenue,NaN,...,NaN,4342419,NaN,NaN,NaN,NaN,NaN,august,21,evening
763,2020-08-26,1900-01-01 23:28:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72 west drive,...,NaN,4342311,NaN,NaN,NaN,NaN,NaN,august,23,evening
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73842,2020-01-03,1900-01-01 21:39:00,brooklyn,11229.0,40.610203,-73.960450,point (-73.96045 40.610203),east 13 street,avenue p,NaN,...,NaN,4269288,NaN,NaN,NaN,NaN,NaN,january,21,evening
74183,2020-01-02,1900-01-01 18:45:00,NaN,NaN,40.810764,-73.952600,point (-73.9526 40.810764),saint nicholas avenue,NaN,NaN,...,NaN,4270691,station wagon/sport utility vehicle,NaN,NaN,NaN,NaN,january,18,evening
74545,2020-01-01,1900-01-01 20:00:00,queens,11692.0,NaN,NaN,NaN,NaN,NaN,5707 shore front parkway,...,NaN,4267983,NaN,NaN,NaN,NaN,NaN,january,20,evening
74712,2020-01-01,1900-01-01 18:57:00,NaN,NaN,40.627070,-74.018650,point (-74.01865 40.62707),bay ridge parkway,7 avenue,NaN,...,NaN,4267703,NaN,NaN,NaN,NaN,NaN,january,18,evening
74733,2020-01-01,1900-01-01 04:28:00,brooklyn,11215.0,40.670070,-73.988160,point (-73.98816 40.67007),NaN,NaN,249 9 street,...,NaN,4269808,NaN,NaN,NaN,NaN,NaN,january,4,night

In [156]:
df.to_parquet("../data/cleaned.parquet",index=False)